-------------------------------------------------------------------------------
Test set: com.revature.BankingAppTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.615 s <<< FAILURE! - in com.revature.BankingAppTest
contextLoads  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.ScriptStatementFailedException: Failed to execute SQL script statement #1 of URL [file:/C:/Users/pinea/Documents/dev/Revature/good-banking/Backend/target/classes/data.sql]: INSERT INTO users (id, email, password) VALUES ( 1, 'testuser@gmail.com', 'password' ); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found; SQL statement:
INSERT INTO users (id, email, password) VALUES ( 1, 'testuser@gmail.com', 'password' ) [42102-200]
Caused by: org.springframework.jdbc.datasource.init.ScriptStatementFailedException: 
Failed to execute SQL script statement #1 of URL [file:/C:/Users/pinea/Documents/dev/Revature/good-banking/Backend/target/classes/data.sql]: INSERT INTO users (id, email, password) VALUES ( 1, 'testuser@gmail.com', 'password' ); nested exception is org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "USERS" not found; SQL statement:
INSERT INTO users (id, email, password) VALUES ( 1, 'testuser@gmail.com', 'password' ) [42102-200]
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: 
Table "USERS" not found; SQL statement:
INSERT INTO users (id, email, password) VALUES ( 1, 'testuser@gmail.com', 'password' ) [42102-200]

